### PR TITLE
Fixing vue warnings

### PR DESCRIPTION
**Pull request by DasGinger**
# Vue - Reactive Data Warning Fixes
- [x] `foe-sheet.vue` - added function to determine rankText and ensure reactive data properties
- [x] `quill-editor.vue` - updated syntax of default property of toolbarOptions object to ensure reactive data
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by DasGinger** [comment]
First time posting a PR... Might need help with the process :).

**Comment by ben** [comment]
Nice, thanks! One small thing: could you add a bullet point to the "in progress" area of changelog.md? You'll see the format there.

**Comment by DasGinger** [comment]
Updated!

**Comment by ben** [comment]
✨ thanks!

**Comment by ben** [comment]
This shipped as part of 1.10.36, so you should be able to get it now. Thanks again!

**Pull request merged**
