### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by WallaceMcGregor**
Updated the Spanish translation with the new keys and translating only with the official Spanish content.

- [ ]
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ben** [comment]
Nice. Is this ready to merge?

**Comment by WallaceMcGregor** [comment]
> Nice. Is this ready to merge?

I think so 😅

**Comment by ben** [comment]
Merged! I just shipped an update, so this will go out in a day or two. Thanks!

**Comment by ben** [comment]
This shipped as part of 1.10.36, so you should be able to get it now. Thanks again!

**Pull request merged**
