### PR TITLE
format all files

### PR DESCRIPTION
**Pull request by rsek**
i've marked it draft because i wanted to be sure it's reproduceable by contributor's development environments before calling it done.

 in other words, if y'all's formatters run on that PR and don't change anything, then no further action needed. if it does turn out different, tho, then at least one person prob needs to reconfigure something, somewhere

### CODE REVIEW

**Comment by ben** [comment]
We should settle on a formatter, because "whatever VS Code is configured for" probably isn't going to cut it. Let's stick with Prettier, since I've already got a config file for it. Want to run `prettier -w '**/*.ts' '**/*.js'` on this branch, or should I?

**Comment by rsek** [comment]
> We should settle on a formatter, because "whatever VS Code is configured for" probably isn't going to cut it. Let's stick with Prettier, since I've already got a config file for it.

in my case it's configured (via extension) to use `.editorconfig`... which, to be fair, is *also* already present on the repo. ;)

i have eslint and prettier plugins active as well; since configurations for all three are present, i assumed that all three configurations were to be applied.

also worth noting: the `.editorconfig` was last touched a month ago. the other two havent been touched for a year. if i had to choose which to prioritize, it'd probably be the `.editorconfig` (which appears to be what's happening currently in my local environment).

Screen Shot 2022-05-31 at 6 21 56 PM
Screen Shot 2022-05-31 at 6 24 15 PM
Screen Shot 2022-05-31 at 6 20 15 PM

i reckon these are all reasonable guesses on my part. obviously, you're gonna know the intent here better than me...but if the provided configurations don't match the intended output when they're actually used, then something about the configurations needs to be changed.

**Comment by ben** [comment]
You're right, the intent here isn't clear. And this project kind of grew over time, so this part wasn't _designed_ really. But I still think it makes sense:

* Editorconfig tells your editor about basic formatting issues, but knows nothing about the language you're working in
* Prettier does bulk code-formatting _very_ well, without much configuration, and knows about JS/TS
* ESlint can check advanced JS/TS issues (extra imports, useless assignments, etc.), but isn't super good at automatic formatting

So we can use these tools for their strengths: prettier for formatting decisions, editorconfig so you don't stray too far from prettier style in the first place, and eslint as a test for detecting deeper issues. We just have to make sure they don't disagree in their settings (which in this case they don't).

I've got my VS Code set to use Prettier for formatting files in this repo. I hate to clobber anyone else's `.vscode/settings.json` file by committing it, so maybe just a note in a CONTRIBUTING.md file would be enough? Or should I go so far as to write a unit test that rejects if `prettier -w '**/*.ts' '**/*.js'` changes anything?

**Comment by rsek** [comment]
yeah, i can see how that setup makes sense. :)

> I've got my VS Code set to use Prettier for formatting files in this repo. I hate to clobber anyone else's `.vscode/settings.json` file by committing it, so maybe just a note in a CONTRIBUTING.md file would be enough?

personally, i'd stick to the standard config files rather than the vscode specific ones - not everyone's necessarily gonna use it. did spot something interesting in the vscode's plugin configuration, though:

Screen Shot 2022-06-08 at 11 29 33 PM

i don't even remember turning on this option. wild. here's what the prettier docs [have to say about it](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options):

Screen Shot 2022-06-08 at 11 31 59 PM

more specific details on what options translate to what [here](https://prettier.io/docs/en/options.html).

here's the current keys set for `[*]` in editorconfig, with the stuff that could be done by prettier (which apparently does support all the languages used in this project) struck out:

- charset = utf-8
- ~~end_of_line = lf~~
- ~~indent_size = 2~~
- ~~indent_style = space~~
- insert_final_newline = true
- ~~max_line_length = 120~~
- ~~tab_width = 2~~

to my knowledge, prettier already adds final newlines, too, so `insert_final_newline` may not be necessary, either. that'd leave `charset` as the sole formatting key in editorconfig - it'd be pretty hard for it to conflict with anything, then!

> Or should I go so far as to write a unit test that rejects if `prettier -w '**/*.ts' '**/*.js'` changes anything?

prettier's docs suggest a pre-commit hook. i don't know much about pre-commit hooks, but there's probably worse ideas than automating it. https://prettier.io/docs/en/precommit.html

**Comment by rsek** [comment]
i'll call this ready for review. `prettierrc.json` is now (nearly) the single source of truth for formatting (and is now JSON rather than TOML). does running with this config produce matching results on your end?

**Comment by rsek** [comment]
TIL: prettier maps `editorconfig`'s `max_line_length` to its `printWidth`, but they don't function exactly the same. [prettier's docs](https://prettier.io/docs/en/options.html#print-width) have this to say about setting `printWidth`:

> For readability we recommend against using more than 80 characters:
> 
> In code styleguides, maximum line length rules are often set to 100 or 120. 
> 
> However, when humans write code, they don’t strive to reach the maximum number of columns on every line. Developers often use whitespace to break up long lines for readability. In practice, the average line length often ends up well below the maximum.
> 
> Prettier’s printWidth option does not work the same way. It is not the hard upper allowed line length limit. It is a way to say to Prettier roughly how long you’d like lines to be. Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.
> 
> Remember, computers are dumb. You need to explicitly tell them what to do, while humans can make their own (implicit) judgements, for example on when to break a line.
> 
> In other words, don’t try to use printWidth as if it was ESLint’s [max-len](https://eslint.org/docs/rules/max-len) – they’re not the same. max-len just says what the maximum allowed line length is, but not what the generally preferred length is – which is what printWidth specifies.

 with that in mind, ive tweaked `.prettierrc.json` to set the target `printWidth` to 80 and run the formatter again. i could see this as a reason to use the `max_line_length` option in `.editorconfig`, though i'm not sure it'd be worth it - IMO all formatting should be coming from a single source.

**Comment by rsek** [comment]
migrated .eslintrc.js to .eslintrc.json to make it easier to take advantage of json schema

**Pull request merged**
