### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by jvir**
Translations update from [Weblate](http://trans.etranslator.eu/projects/foundry-ironsworn/sistema/) for Foundry Ironsworn/Sistema.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by ben** [comment]
Looks like `es.json` is an empty hash so far. Let me know when you're ready for a review/merge.

**Comment by NeV3rKilL** [comment]
It's already advanced. I just did it few minutes ago.

The "BURN" tab does not adapt to the text.

Difficulties are hardcoded on the PC sheet. Conditions and effects too.
https://i.imgur.com/P2ys0Nb.jpg

If you want I could make a pull requests with these changes.

Thanks

**Comment by ben** [comment]
Ooooh, good catch! Yeah, I'd love that. Do you want to do that here, or on a separate PR?

**Comment by ben** [comment]
I went ahead and fixed the issues you mentioned, as well as a couple more. Does #26 work okay for you?

**Comment by ben** [comment]
#26 is merged, and I'm going to ship a release. Let me know when this seems ready!

**Comment by NeV3rKilL** [comment]
I can finish the translation for the rest of the movements to Spanish for this evening.

I could not test it until this evening too.

**Comment by NeV3rKilL** [comment]
All the texts and movements of the Ironsworn core should be translated to Spanish. I'll do the testing this evening.

**Comment by NeV3rKilL** [comment]
Hello,

I checked, and fixed some mistakes.

The most disrupting issue atm are the roll links. https://i.imgur.com/dj7J96A.jpg and same happen in the chatmessages https://i.imgur.com/bYmSE3z.jpg

Also, but this is minor:

The debilities:
https://i.imgur.com/icdLEeF.jpg

and the movements titles:
https://i.imgur.com/DI2WT3R.jpg

Thanks for fixing the previous reports ;)

**Comment by ben** [comment]
Hi! I went ahead and noted the bugs in #27, so this should be ready to merge. Thanks so much!

**Pull request merged**
